contentdir = "content"
theme = "hugo-base-theme"
languageCode = "en-us"
title = "Choria"
googleAnalytics = "UA-10152852-12"

[params]
    mainIcon = "img/choria-vert-400px.png"

[[params.social]]
    title = "docs"
    url = "docs/about/"
    button = "primary"

[[params.social]]
    title = "github"
    url = "https://github.com/choria-io"
    button = "success"

[[params.social]]
    title = "blog"
    url = "blog/"
    button = "info"

[[params.social]]
    title = "community"
    url = "https://github.com/choria-io/general/discussions"
    button = "primary"
